### ISSUE TITLE
Delete resource is only partially deleted

### ISSUE THREAD

**Issue by coreation** [njh/easyrdf#245] opened 2015-07-07 10:21 UTC
I'm having an issue with the deleteResource functionality in an EasyRdf_Graph. In the JSON-blob below you'll find the json-ld representation of the eventual graph. So what I do is I make a resource "http://dapps.dev/105#dataset", which links with a distribution (identified by #distribution). It's possible to store the graph, read and change it. So in this blob, first the dataset was created together with a distribution (#106), then stored. Then I read it back again into a graph, delete the distribution resource (#106) and add a new one (#107). The resource is indeed no longer linked to the 105#dataset, but it is still in the graph. As you can see in the JSON, the dcat:distribution has now a link-value only to the #107, no longer to the #106. 

So my question is how do I get rid of a resource in graph competely, because if you think further, removing and adding distributions, the graph will only get bigger...

```json
{
    "_id" : ObjectId("55978582972cbbe2dfb7acd9"),
    "@context" : {
        "dcat" : "http://www.w3.org/ns/dcat#",
        "dc" : "http://purl.org/dc/elements/1.1/",
        "rdfs" : "http://www.w3.org/2000/01/rdf-schema#",
        "rdf" : "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
        "dct" : "http://purl.org/dc/terms/",
        "linda" : "http://semweb.mmlab.be/ns/linda#",
        "foaf" : "http://xmlns.com/foaf/0.1/",
        "odapps" : "http://semweb.mmlab.be/ns/odapps#"
    },
    "@graph" : [ 
        {
            "@id" : "http://dapps.dev/105",
            "@type" : "dcat:CatalogRecord",
            "dct:contributor" : "http://dapps.dev/user/John",
            "dct:creator" : {
                "@id" : "http://dapps.dev/user/admin"
            },
            "dct:issued" : NumberLong(1435992985),
            "dct:modified" : NumberLong(1435992985),
            "rdfs:comment" : "qsdfqsfqs\ndf\ndqsf\nsdq\nf",
            "http://xmlns.com/foaf/spec/primaryTopic" : {
                "@id" : "http://dapps.dev/105#dataset"
            }
        }, 
        {
            "@id" : "http://dapps.dev/105#dataset",
            "@type" : "dcat:Dataset",
            "dct:accrualPeriodicity" : "",
            "dct:description" : "qsdfqs\nfqsd\nfdsq\nfqs",
            "dct:title" : "dataset1",
            "linda:recommendation" : "",
            "linda:score" : "",
            "rdfs:comment" : "qsdfqsdf",
            "rdfs:seeAlso" : {
                "@id" : "http://google.com"
            },
            "dcat:distribution" : {
                "@id" : "http://dapps.dev/105#distribution107"
            },
            "dcat:keyword" : [ 
                "qsdf", 
                "fqsd", 
                "qsdfqfs", 
                "qdsf"
            ]
        }, 
        {
            "@id" : "http://dapps.dev/105#distribution106",
            "@type" : "dcat:Distribution",
            "dct:license" : {
                "@id" : "http://opendataforum.info/Docs/licenties/BV.htm"
            },
            "linda:useFor" : {
                "@id" : "linda:EnvironmentalControl"
            }
        }, 
        {
            "@id" : "http://dapps.dev/105#distribution107",
            "@type" : "dcat:Distribution",
            "dct:license" : {
                "@id" : "http://opendataforum.info/Docs/licenties/BV.htm"
            },
            "linda:useFor" : {
                "@id" : "linda:EnvironmentalControl"
            }
        }
    ]
}
```

**Comment by njh** [comment] 2015-07-08 21:39
Sorry to keep asking for more information but do have some example PHP showing what you are doing?

**Comment by coreation** [comment] 2015-07-09 07:31
No problem, happy too :) Anything to lead us to the source of the problem (me not using the lib correctly or small bug in the lib)

So I fetch all of the distributions and delete them one by one, so that I can then only add the ones that they've given in the front-end (no need to put that code here).

So I think the relevant code is the following, taking each distribution and delete them from the graph.

```php
foreach ($graph->allOfType('dcat:Distribution') as $distribution) {

    $resource = $graph->resource($uri . "#dataset");

    $graph->deleteResource($resource, 'dcat:distribution', $distribution->getUri());
}

```

**Comment by coreation** [comment] 2015-07-15 14:04
Hey @njh! Is the PHP code sufficient?

**Comment by coreation** [comment] 2015-08-12 14:41
Hey @njh , probably busy because of the summer ;) If you need more info, let me know!

**Comment by coreation** [comment] 2015-09-07 13:59
@njh bump? :)

**Comment by njh** [comment] 2015-09-09 09:01
Very sorry @coreation. Far too much going on in my life!
Will try and respond later today.

**Comment by njh** [comment] 2015-09-10 18:39
Hello Jan,

Sorry it has taken me so long to respond - I think the problem is that there isn't a generic way of doing a recursive delete, without going too far.

For example in this example:

```
                                                                 ┌─────────┐             
                                         ┌────────foaf:name ────▶│   Bob   │             
                                         │                       └─────────┘             
                                         │                                               
┌──────────────────────┐   foaf:    ┌─────────┐                  ┌──────────────────────┐
│  http://cheese.com/  │◀ interest ─│Person 1 │──foaf:homepage──▶│ http://example.com/  │
└──────────────────────┘            └─────────┘                  └──────────────────────┘
            ▲                            │                                               
            │                        foaf:knows                                          
            │                            │                                               
            │                            ▼                                               
            │         foaf:         ┌─────────┐                  ┌─────────┐             
            └─────── interest ──────│Person 2 │──── foaf:name ──▶│  Alice  │             
                                    └─────────┘                  └─────────┘             
```

Your goal is to delete 'Person 1', 'Bob' and 'http://example.com' ?

But I am not sure it is possible to know that it shouldn't also delete 'Person 2'.

It gets more complex when there are deep branches on the graph, that logically 'belong' to a parent resource.

There are a couple of options:
# Custom logic in your application to know what/how to delete an entity.
# Add an option to EasyRdf to choose how deep to delete.

Did I understand correctly?

And yes, I think this is a duplicate of #232

**Comment by coreation** [comment] 2015-09-10 19:07
Yes, I think that might be the case as you so drew. It was also my only internal remark on how such a deletion mechanism should work. I'll have to simulate it then on application level ;) Thanks!

**Closed** 2016-02-12 09:20 UTC
